include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_relative_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true