include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    prefer_relative_imports: true
    # sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true